### ISSUE TITLE
[DEPLOY] 배포 작업

### ISSUE THREAD

**Issue by sena-22** [wanted-pre-onboarding-team-9/pre-onboarding-10th-1-9#20]
### 🤸 Describe the required feature

- [X] Deploy

### 🏊 Todo

- [X] Heroku를 통해 배포

**Comment by SangWoo9734** [comment]
Heroku를 통해서 프로젝트 배포 완료했습니다. 그리고 레포지토리 About란에 해당 링크 추가해두었습니다.

 [LInk](https://pre-onboarding-10th-1-9.herokuapp.com/)

해당 이슈는 종료합니다.
